### ISSUE TITLE
metadata 格式不符合 YAML 格式

### ISSUE THREAD

**Issue by Soulter** [Ynkcc/astrbot_plugin_MultiAI_PollPad#1]
metadata 格式不符合 YAML 格式导致 AstrBot 服务器无法正确解析该文件

```yaml
name: MultiAI_PollPad # 这是你的插件的唯一识别名。
desc: 轮询调用配置的大语言模型，以输出多个结果。同时将ai的结果拷贝至在线文本编辑器，以便于用户复制。 # 插件简短描述
name: MultiAI_PollPad # 这是你的插件的唯一识别名。
help: 输入 /multiai 和你的问题 进行调用
version: v0.2.0 # 插件版本号。格式：v1.1.1 或者 v1.1
author: [ynkcc](https://github.com/ynkcc) # 作者
repo: https://github.com/ynkcc/astrbot_plugin_MultiAI_PollPad # 插件的仓库地址
```

author 只写 ynkcc 即可了
